spring:
  application:
    name: batch-app
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql
